import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { neobrutalism } from "@clerk/themes";
import {
  ClerkProvider,
  SignInButton,
  SignUp,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
      }}
    >
      <html lang="en">
        <body className="min-h-screen flex items-center justify-center relative">

          {/* Background image */}
          <div
            className="absolute inset-0 z-0 bg-cover bg-center"
            style={{
              backgroundImage: "url('/abstract-textured-background.jpg')", // ✅ Correct usage
              filter: 'brightness(0.6)',
            }}
          />


          {/* Foreground content */}
          <div className="relative z-10 w-full flex justify-center items-center">
            {children}
          </div>

        </body>
      </html>
    </ClerkProvider>
  )
}